apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

patches:
- path: broadcaster-patch.yaml
- path: backend-patch.yaml

images:
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/devops-course-503807/dwk-images/broadcaster
  newTag: 43102eb3fd0fa99cee4552808af7597327f47c19
- name: PROJECT/TODO_APP
  newName: europe-north1-docker.pkg.dev/devops-course-503807/dwk-images/todo-app
  newTag: 43102eb3fd0fa99cee4552808af7597327f47c19
- name: PROJECT/TODO_BACKEND
  newName: europe-north1-docker.pkg.dev/devops-course-503807/dwk-images/todo-backend
  newTag: 43102eb3fd0fa99cee4552808af7597327f47c19
