apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- backup-cronjob.yaml

patches:
- path: broadcaster-patch.yaml
- path: backend-patch.yaml

images:
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/devops-course-503807/dwk-images/broadcaster
  newTag: 276f2e4b4412e7b341c21f6741a1b49071b99595
- name: PROJECT/TODO_APP
  newName: europe-north1-docker.pkg.dev/devops-course-503807/dwk-images/todo-app
  newTag: 276f2e4b4412e7b341c21f6741a1b49071b99595
- name: PROJECT/TODO_BACKEND
  newName: europe-north1-docker.pkg.dev/devops-course-503807/dwk-images/todo-backend
  newTag: 276f2e4b4412e7b341c21f6741a1b49071b99595
