apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: project
  name: todo-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: todo-backend

  template:
    metadata:
      labels:
        app: todo-backend

    spec:
      containers:
        - name: todo-backend
          image: PROJECT/TODO_BACKEND
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1

          livenessProbe:
            httpGet:
              path: /livez
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          env:
            - name: PORT
              value: "3000"

            - name: MAX_TODO_LENGTH
              value: "140"

            - name: POSTGRES_HOST
              value: todo-postgres-svc

            - name: POSTGRES_PORT
              value: "5432"

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: postgres

            - name: POSTGRES_DB
              value: todos

            - name: NATS_URL
              value: "nats://my-nats.nats.svc.cluster.local:4222"

            - name: NATS_SUBJECT
              value: "todo.events"
