apiVersion: apps/v1
kind: Deployment

metadata:
  name: broadcaster
  namespace: project

spec:
  replicas: 1

  selector:
    matchLabels:
      app: broadcaster

  template:
    metadata:
      labels:
        app: broadcaster

    spec:
      containers:
        - name: broadcaster
          image: PROJECT/BROADCASTER
          imagePullPolicy: Always

          env:
            - name: NATS_URL
              value: "nats://my-nats.nats.svc.cluster.local:4222"

            - name: NATS_SUBJECT
              value: "todo.events"

            - name: WEBHOOK_URL
              value: "https://webhook.site/bc3e95b4-0816-4415-b14a-90f1701bed69"

          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"

            limits:
              cpu: "100m"
              memory: "128Mi"
