apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - persistentvolumeclaim.yaml
  - configmap.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - cronjob.yaml
  - ingress.yaml
  - broadcaster-deployment.yaml
  - postgres.yaml
  - backend-service.yaml
  - backend-deployment.yaml
